import { CurrentPageProvider } from "@/store/CurrentProvider";
import { Menu } from "../../components/molecules/menu/Menu";
import "./globals.css";
import { Roboto } from "next/font/google";
import ProviderReservation from "@/store/ProviderReservation";

const fonts = Roboto({ subsets: ["latin"], weight: ["400"] });

export const metadata = {
  title: "NivaGo",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ProviderReservation>
      <CurrentPageProvider>
        <body className={fonts.className}>
          <Menu />
          {children}
        </body>
      </CurrentPageProvider>
      </ProviderReservation>
    </html>
  );
}
