import { Menu } from '../../components/molecules/menu/Menu'
import './globals.css'
import { Pacifico } from 'next/font/google'

const fonts = Pacifico ({ subsets: ['latin'], weight:['400']})

export const metadata = {
  title: 'NivaGo',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={fonts.className}>
        <Menu />
        {children}
        </body>
    </html>
  )
}
